spring:
  cloud:
    gateway:
      routes:
        - id: msvc-product
          uri: lb://msvc-product
          predicates:
            - Path=/api/product/**
            - Header=token, 12345
            - Method=GET, POST
            - Query=color, verde
            - Cookie=color, azul
            - Header= content-type, application/json
          filters:
            - StripPrefix=2
            - EjemploCookie=Hi this is my personalized message, user, Juan
#            - name: SampleCookie
#              args:
#                name: user
#                value: Juan
#                message: Hi, this is my personalized message
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, bar
            - AddResponseHeader=token-response, foo
            - AddRequestParameter=name, Juan
            - SetResponseHeader=content-type, text/plain